use_default_settings: true

general:
  instance_name: "MCP Search"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey123changeme"
  limiter: false
  image_proxy: false
  public_instance: false

ui:
  default_theme: simple
  default_locale: en
